/**
 * Exports, inline output formats, identifier lookups, status reporting and
 * non-ASCII / space-containing paths.
 */

import fs from "node:fs";
import path from "node:path";

import {
  byId,
  createReporter,
  defaultTarget,
  describeTarget,
  freshDir,
  mcpBatch,
  REPO_ROOT,
  session,
  toolCall,
  toolJson,
} from "./harness.mjs";
import { startMockServer } from "./mock-ieee-server.mjs";

const API_KEY = "0123456789abcdef0123456789abcdef";

function baseEnv(mock, stateDir, extra = {}) {
  return {
    IEEE_API_KEY: API_KEY,
    IEEE_API_BASE: mock.baseUrl,
    IEEE_MCP_STATE_DIR: stateDir,
    IEEE_LOG_LEVEL: "warn",
    IEEE_DAILY_BUDGET: "200",
    ...extra,
  };
}

export async function run() {
  const reporter = createReporter("export");
  const target = defaultTarget();
  reporter.note(`target: ${describeTarget()}`);
  const mock = await startMockServer();

  try {
    // A working directory with non-ASCII characters and spaces.
    const unicodeDir = path.join(REPO_ROOT, ".tmp", "runs", "中文 目录 with spaces");
    fs.rmSync(unicodeDir, { recursive: true, force: true });
    fs.mkdirSync(unicodeDir, { recursive: true });

    const stateDir = freshDir("export");
    mock.state.requests.length = 0;

    // ── search then export ───────────────────────────────────────────────────
    reporter.section("export from search_id");
    const run = await mcpBatch(target, {
      label: "export-search",
      cwd: unicodeDir,
      env: baseEnv(mock, stateDir),
      requests: session([
        toolCall(2, "search_papers", { querytext: "beamforming export", max_records: 6 }),
        toolCall(3, "search_papers", { querytext: "inline csv", max_records: 3, output_format: "csv" }),
        toolCall(4, "search_papers", { querytext: "inline md", max_records: 3, output_format: "markdown" }),
        toolCall(5, "search_papers", { querytext: "inline bib", max_records: 3, output_format: "bibtex" }),
        toolCall(6, "export_results", { search_id: "srch_doesnotexist", format: "csv" }),
      ]),
    });

    const searchPayload = toolJson(byId(run.responses, 2));
    const searchId = searchPayload?.search_id;
    reporter.check("search returned a search_id", typeof searchId === "string" && searchId.startsWith("srch_"), String(searchId));
    reporter.check(
      "unknown search_id is rejected",
      byId(run.responses, 6)?.result?.isError === true,
      byId(run.responses, 6)?.result?.content?.[0]?.text
    );

    // ── inline output formats ────────────────────────────────────────────────
    reporter.section("inline output formats");
    const csvText = byId(run.responses, 3)?.result?.content?.[0]?.text ?? "";
    const mdText = byId(run.responses, 4)?.result?.content?.[0]?.text ?? "";
    const bibText = byId(run.responses, 5)?.result?.content?.[0]?.text ?? "";
    reporter.check("csv output starts with a BOM and a header", csvText.startsWith("\uFEFFarticle_number,doi,title"), JSON.stringify(csvText.slice(0, 80)));
    reporter.check("csv output quotes embedded commas", csvText.includes('"'), csvText.slice(0, 300));
    reporter.check("markdown output documents the scope", mdText.includes("metadata + abstract (NOT full text)"), mdText.slice(0, 200));
    reporter.check("markdown output reports pagination", mdText.includes("has_more:"), mdText.slice(0, 400));
    reporter.check("markdown output marks missing fields", mdText.includes("Missing fields:") || mdText.includes("(not returned by IEEE)"), mdText.slice(0, 1200));
    reporter.check("bibtex output has a provenance header", bibText.startsWith("% Generated by ieee-mcp"), bibText.slice(0, 120));
    reporter.check("bibtex output contains entries", /@(article|inproceedings|misc)\{/.test(bibText), bibText.slice(0, 400));
    reporter.check("bibtex output carries the query conditions", bibText.includes("inline bib"), bibText.slice(0, 300));

    // ── real export run, now that the search_id is known ─────────────────────
    reporter.section("export files on disk");
    const exportRun = await mcpBatch(target, {
      label: "export-files",
      cwd: unicodeDir,
      env: baseEnv(mock, stateDir),
      requests: session([
        toolCall(2, "export_results", { search_id: searchId, format: "csv", output_path: "结果 目录/论文列表.csv" }),
        toolCall(3, "export_results", { search_id: searchId, format: "json", output_path: "结果 目录/论文列表.json" }),
        toolCall(4, "export_results", { search_id: searchId, format: "bibtex", output_path: "结果 目录/参考文献" }),
      ]),
    });

    const csvOutcome = toolJson(byId(exportRun.responses, 2));
    const jsonOutcome = toolJson(byId(exportRun.responses, 3));
    const bibOutcome = toolJson(byId(exportRun.responses, 4));

    reporter.check("csv export reports an absolute path under the Unicode cwd", csvOutcome?.output_path?.startsWith(unicodeDir), JSON.stringify(csvOutcome));
    reporter.check("csv export reported ok", csvOutcome?.ok === true, JSON.stringify(csvOutcome));
    reporter.check("csv file exists", fs.existsSync(csvOutcome?.output_path ?? ""), csvOutcome?.output_path);
    reporter.check("csv sidecar exists", fs.existsSync(csvOutcome?.sidecar_path ?? ""), csvOutcome?.sidecar_path);
    reporter.equal("csv export counted 6 records", csvOutcome?.records, 6);
    reporter.equal("csv encoding is declared", csvOutcome?.encoding, "UTF-8 with BOM");
    reporter.check("csv sha256 is reported", /^[0-9a-f]{64}$/.test(csvOutcome?.sha256 ?? ""), csvOutcome?.sha256);

    if (fs.existsSync(csvOutcome?.output_path ?? "")) {
      const csvBytes = fs.readFileSync(csvOutcome.output_path);
      reporter.check("csv starts with a UTF-8 BOM on disk", csvBytes[0] === 0xef && csvBytes[1] === 0xbb && csvBytes[2] === 0xbf);
      const csvContent = csvBytes.toString("utf8").replace(/^\uFEFF/, "");
      const lines = csvContent.split("\r\n").filter((line) => line.length > 0);
      reporter.equal("csv has a header plus 6 rows", lines.length, 7);
      reporter.check("csv header has the provenance columns", lines[0].includes("source") && lines[0].includes("query_id"), lines[0]);
      reporter.check("csv preserves Chinese titles", /[\u4e00-\u9fff]/.test(csvContent), "no CJK found");
    }

    const sidecar = JSON.parse(fs.existsSync(csvOutcome?.sidecar_path ?? "") ? fs.readFileSync(csvOutcome.sidecar_path, "utf8") : "{}");
    reporter.equal("sidecar records the source database", sidecar.source, "IEEE Xplore");
    reporter.equal("sidecar records the search_id", sidecar.searchId, searchId);
    reporter.check("sidecar records the search conditions", JSON.stringify(sidecar.query).includes("beamforming export"), JSON.stringify(sidecar.query));
    reporter.check("sidecar records the retrieval timestamp", typeof sidecar.retrievedAt === "string", sidecar.retrievedAt);
    reporter.equal("sidecar records the scope", sidecar.searchScope, "metadata_and_abstract");

    reporter.check("json export file exists", fs.existsSync(jsonOutcome?.output_path ?? ""), jsonOutcome?.output_path);
    if (fs.existsSync(jsonOutcome?.output_path ?? "")) {
      const parsed = JSON.parse(fs.readFileSync(jsonOutcome.output_path, "utf8"));
      reporter.check("json export embeds meta", parsed.meta?.source === "IEEE Xplore", JSON.stringify(parsed.meta)?.slice(0, 200));
      reporter.equal("json export embeds records", parsed.records?.length, 6);
      reporter.check("json export records keep missing_fields", Array.isArray(parsed.records?.[0]?.missing_fields));
    }

    reporter.check("bibtex extension is filled in when omitted", bibOutcome?.output_path?.endsWith(".bib"), bibOutcome?.output_path);
    if (fs.existsSync(bibOutcome?.output_path ?? "")) {
      const bib = fs.readFileSync(bibOutcome.output_path, "utf8");
      reporter.check("bibtex file carries the provenance comment", bib.includes(`% search_id: ${searchId}`), bib.slice(0, 260));
      reporter.check("bibtex file carries the query conditions", bib.includes("beamforming export"));
      reporter.check("bibtex file has 6 entries", (bib.match(/^@/gm) ?? []).length === 6, String((bib.match(/^@/gm) ?? []).length));
    }

    // ── export from an explicit record list ──────────────────────────────────
    reporter.section("export explicit records");
    const manualRun = await mcpBatch(target, {
      label: "export-manual",
      cwd: unicodeDir,
      env: baseEnv(mock, stateDir),
      requests: session([
        toolCall(2, "export_results", {
          format: "json",
          output_path: "manual/手动记录.json",
          records: [
            {
              article_number: "42",
              title: "Manual record",
              doi: "10.1109/MANUAL.2024.1",
              authors: { authors: [{ full_name: "Manual Author", affiliation: "Somewhere" }] },
            },
          ],
        }),
        toolCall(3, "export_results", { format: "csv", records: [] }),
      ]),
    });
    const manualOutcome = toolJson(byId(manualRun.responses, 2));
    reporter.equal("explicit records exported", manualOutcome?.records, 1);
    reporter.check("empty record list is rejected", byId(manualRun.responses, 3)?.result?.isError === true);

    // ── identifier lookup ────────────────────────────────────────────────────
    reporter.section("identifier lookups");
    mock.state.requests.length = 0;
    const lookupRun = await mcpBatch(target, {
      label: "lookups",
      env: baseEnv(mock, freshDir("export-lookup")),
      requests: session([
        toolCall(2, "get_paper_details", { article_number: "1000001" }),
        toolCall(3, "get_paper_details", { doi: "10.1109/TEST.2024.1001" }),
        toolCall(4, "get_paper_details", {}),
        toolCall(5, "get_paper_citations", { article_number: "1000003" }),
      ]),
    });
    const details = toolJson(byId(lookupRun.responses, 2));
    reporter.equal("article_number lookup returns one record", details?.returned_records, 1);
    reporter.equal("article_number matches", details?.articles?.[0]?.article_number, "1000001");
    reporter.check("details include affiliations", Boolean(details?.articles?.[0]?.authors?.[0]?.affiliation));
    reporter.check("details include abstract", typeof details?.articles?.[0]?.abstract === "string");
    const queryParamsOf = (request) =>
      Object.keys(request?.params ?? {})
        .filter((key) => !["max_records", "start_record", "apikey"].includes(key))
        .join(",");
    reporter.equal("article_number lookup sends only article_number", queryParamsOf(mock.state.requests[0]), "article_number");
    reporter.equal("doi lookup sends only doi", queryParamsOf(mock.state.requests[1]), "doi");
    const noArgs = JSON.parse(byId(lookupRun.responses, 4)?.result?.content?.[0]?.text ?? "{}");
    reporter.check("missing identifier is rejected", byId(lookupRun.responses, 4)?.result?.isError === true);
    reporter.equal("missing identifier error code", noArgs.code, "INPUT_ERROR");

    const citations = toolJson(byId(lookupRun.responses, 5));
    reporter.equal("citations report the article number", citations?.article_number, "1000003");
    reporter.equal("citations report the paper count", citations?.citing_paper_count, 9);
    reporter.equal("citations report the patent count", citations?.citing_patent_count, 3);

    // ── status tool ──────────────────────────────────────────────────────────
    reporter.section("ieee_status");
    const statusRun = await mcpBatch(target, {
      label: "status",
      env: baseEnv(mock, stateDir),
      requests: session([
        toolCall(2, "ieee_status", {}),
        toolCall(3, "ieee_status", { include_config: false }),
      ]),
    });
    const status = toolJson(byId(statusRun.responses, 2));
    reporter.equal("status reports the server name", status?.server, "ieee-mcp 2.0.0");
    reporter.equal("status reports the key as present", status?.config?.api_key_present, true);
    reporter.check("status exposes only a hashed key fingerprint", /^[0-9a-f]{12}$/.test(status?.config?.api_key_fingerprint_sha256_12 ?? ""), status?.config?.api_key_fingerprint_sha256_12);
    reporter.check("status reports the local usage ledger", typeof status?.local_usage?.ledger_file === "string");
    reporter.check(
      "status repeats the local-only disclaimer",
      /NOT the official IEEE remaining quota/i.test(status?.local_usage?.disclaimer ?? ""),
      status?.local_usage?.disclaimer
    );
    reporter.check("status reports cache statistics", typeof status?.cache?.entries === "number");
    reporter.check("status reports the rate-limit header snapshot", typeof status?.last_ieee_rate_limit_headers === "object");
    reporter.check("status output contains no API key", !JSON.stringify(status).includes(API_KEY));
    const statusNoConfig = toolJson(byId(statusRun.responses, 3));
    reporter.equal("include_config=false omits the config block", statusNoConfig?.config, undefined);
  } finally {
    await mock.close();
  }

  return reporter.summary();
}
